version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: ngiinx
    ports:
      - "8090:8090"
      - "8008:8008"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./local:/usr/share/nginx/html/local
      - ./htpasswd:/etc/nginx/.htpasswd:ro
      - ./cert.pem:/etc/ssl/certs/cert.pem:ro
      - ./key.pem:/etc/ssl/private/key.pem:ro
    restart: always
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
